### ISSUE TITLE
version 0.15.0 on pypi does not include 'session' fix  in setup.py

### ISSUE THREAD

**Issue by gkontos89** [concordion/pyconcordion2#25]
#23 does not appear to be included in version 0.15.0 on the pypi repository.  I was having issues pip installing normally, so I downloaded the .tar.gz.  Unzipped the setup.py did not have the fix where 
`session=False`

**Comment by johnjiang** [comment]
Deployed 0.15.1 with https://github.com/concordion/pyconcordion2/commit/381af587ffc73d7a84d64cdbf715fe18bb077aab
